apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "hook-demo.fullname" . }}-test-up"
  labels:
    {{- include "hook-demo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
#    "helm.sh/hook-weight": "-5"
#    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: test-up
      image: busybox
      command: ['sh', '-c', 'echo hook is running && sleep 10']

