apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
    replicas: 2 # This is the number of pods that will be created
    selector:
      matchLabels:
        app: nginx
    template:
        metadata:
            labels:
              app: nginx
        spec:
          containers:
            - name: nginx-container
              image: nginx:1.27.0
              envFrom:
                - configMapRef:
                    name: app-config
              env:
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: my-secret
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: my-secret
          volumes:
            - name: my-volume
              persistentVolumeClaim:
                claimName: my-pvc
                