apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
    replicas: 2 # This is the number of pods that will be created
    selector:
      matchLabels:
        app: nginx
    template:
        metadata:
            labels:
              app: nginx
        spec:
          containers:
            - name: nginx-container
              image: nginx:1.27.0