apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: nginx
type: Opaque 
data:
  username: dXNlcm5hbWU= #base64 encoded username: username
  password: cGFzc3dvcmQ= #base64 encoded password: password
  
  
#WARNING: You should not place the username and password in the version control repository or anywhere 
# else in plain text even if base64 encoded, it's simple to decode. That is just for demonstration purposes!

#Instead, in RIDER IDE use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
