apiVersion: v1
kind: Secret
metadata:
  name: my-mysql-secret
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWxwYXNzd29yZA==
  MYSQL_USER: bXlzcWw=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: d29yZHByZXNz
