apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.wordpress.svc.cluster.local
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-mysql-secret
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mysql-secret
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-mysql-secret
                  key: MYSQL_DATABASE
            - name: WPLANG
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WPLANG
            - name: WP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WP_DEBUG
          resources:
            requests:
              memory: "256Mi" 
              cpu: "0.25"     
            limits:
              memory: "512Mi" 
              cpu: "0.5"      
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc    
        - name: wordpress-config-volume
          configMap:
            name: wordpress-config
