apiVersion: v1
kind: Secret
metadata:
  name: my-demo-projekt-secret-v2
  namespace: demo-projekt-v2 
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: bXlzcWxwYXNzd29yZA== #base64 encoded password: mysqlpassword
    MYSQL_USER: bXlzcWw= #base64 encoded username: mysql
    MYSQL_PASSWORD: cGFzc3dvcmQ= #base64 encoded password: password
    MYSQL_DATABASE: d29yZHByZXNz #base64 encoded database: wordpress
    
#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
