apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywordpress-deployment-v2
  namespace: demo-projekt-v2  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywordpress-pod-v2
  template:
    metadata:
      labels:
        app: mywordpress-pod-v2 
    spec:
      containers:
        - name: mywordpress-container
          image: wordpress:latest
          
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-svc-v2.demo-projekt-v2.svc.cluster.local # format: service-name.namespace.svc.cluster.local
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-demo-projekt-secret-v2
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-demo-projekt-secret-v2
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-demo-projekt-secret-v2
                  key: MYSQL_DATABASE
            - name: WPLANG
              valueFrom:
                configMapKeyRef:
                  name: wordpress-app-config-v2
                  key: WPLANG
            - name: WP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: wordpress-app-config-v2
                  key: WP_DEBUG                           
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.25"
            limits:
              memory: "2Gi"
              cpu: "0.5"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mywordpress-volume
              mountPath: /var/www/html
      volumes:
        - name: mywordpress-volume
          persistentVolumeClaim:
            claimName: mywordpress-pvc-v2
        - name: mywordpress-config-volume
          configMap:
            name: wordpress-app-config-v2