apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- with .Values.service.ports }}
  - port: {{ .http.port }}
    targetPort: {{ .http.targetPort }}
    protocol: {{ .http.protocol }}
    name: {{ .http.name }}
  - port: {{ .https.port }}
    protocol: {{ .https.protocol }}
    name: {{ .https.name }}
  {{- end }}
  selector:
    app: {{ .Values.service.selector.app }}