apiVersion: v1
kind: Secret
metadata:
  name: my-demo-projekt-secret
  namespace: demo-projekt
type: Opaque
data:
  username: ZGV2ZWxvcGVy #base64 encoded username: developer
  password: cGFzc3dvcmQ= #base64 encoded password: password

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
